spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pfk_workspace
    username: pfkuser
    password: pfkpassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret:
    key: mySuperSecretKeyForJwtSigning
  expiration:
    access-token: 900000 # 15 minutes
    refresh-token: 604800000 # 7 days

aws:
  s3:
    bucket: pfk-workspace-files
  region: eu-west-2
